### ISSUE TITLE
Snyk Broker not starting: Illegal operation on a directory

### ISSUE THREAD

**Issue by bt-nia** [snyk/broker#318]
I set up the current snyk-broker version via GCPs Cloud Run via Kubernetes. Unfortunately, the container does not spawn correctly. From the log I can see the default config is being created (filters appear and the server listens on 8080), but an error prevents the container from spinning up completely:
```
Error: EISDIR: illegal operation on a directory, read
    at main (/home/node/.npm-global/lib/node_modules/snyk-broker/dist/lib/webserver.js:37:25)
    at Object.module.exports [as client] (/home/node/.npm-global/lib/node_modules/snyk-broker/dist/lib/client/index.js:21:52)
    at Object.main (/home/node/.npm-global/lib/node_modules/snyk-broker/dist/lib/index.js:34:23)
    at module.exports (/home/node/.npm-global/lib/node_modules/snyk-broker/dist/cli/exec.js:8:42)
    at Object.<anonymous> (/home/node/.npm-global/lib/node_modules/snyk-broker/dist/cli/index.js:22:5) {
```

My config:
![image](https://user-images.githubusercontent.com/74181389/114724723-276d3880-9d3c-11eb-8515-05185b53f1b2.png)

Any idea what directory is being accessed illegally here?

**Comment by bt-nia** [comment]
Ok, that was a misconfig on my end. I'm not supposed to give the full directory as the mount path, but only the actual directory and reference the secret name in the `HTTPS_KEY` and `HTTPS_CERT` variable like so:
`HTTPS_CERT = /private/cert/snyk-broker-selfsigned-tls-cert`
